### ISSUE TITLE
Global notice with `<ul>` breaks option page

### ISSUE THREAD

**Issue by matzeeable** [wpzoom/Social-Icons-Widget-by-WPZOOM#26]
Hey!

When I add the following notice to my website, it breaks the option page of Social Icons:

```php
add_action('admin_notices', function () {
    echo sprintf(
        '<div class="notice notice-warning"><p>%s</p><ul><li>%s</li></ul><p>%s</p></div>',
        'This is my global notice!',
        'a li element',
        'Another text'
    );
});
```

![image](https://user-images.githubusercontent.com/1008534/134358358-0eb211ee-8c5d-44b9-bfa8-4ad94d5c42a9.png)

But if I remove the `ul` from the notice, it is working as expected:

```php
add_action('admin_notices', function () {
    echo sprintf(
        '<div class="notice notice-warning"><p>%s</p>%s<p>%s</p></div>',
        'This is my global notice!',
        'a li element',
        'Another text'
    );
});
```

![image](https://user-images.githubusercontent.com/1008534/134358615-27e30c04-5459-48af-b722-f53cca7bbdce.png)

I had a look at your code, but I do not understand what could cause the issue. Can you please check this? 😊

**Comment by Alexus450** [comment]
Hi @matzeeable! Thanks for reporting, we fixed this issue.
