### ISSUE TITLE
Font Awesome icons in widget versus in block

### ISSUE THREAD

**Issue by tiny-moo** [wpzoom/Social-Icons-Widget-by-WPZOOM#28]
Hello,

I've run into an issue in 4.2.3 with one specific icon, but I'm worried it might be a symptom of a larger problem, so I thought I'd mention it, just in case.

I'm trying to use the regular old Amazon icon, which is in the Font Awesome 5 icon collection (and appears under "Font Awesome Brands" in the interface).  If I'm adding this icon in a block on the page, everything seems to work just fine -- the span tag has a class of "social-icon fa fa-amazon" and everything renders as expected.  If I'm adding this icon in a widget, say, in the footer, the span class is "social-icon fab fa-amazon" and it renders a little goofy.  

I can see where this is happening -- around lines 198-218 of social-icons-widget-by-wpzoom.php the $categories_list array is set to either one general Font Awesome set or three Font Awesome subsets depending on whether editing a widget or a block, but the interface for selecting the icon kit in the admin interface seems to be identical for both widgets and blocks.  

This isn't anything that can't be tweaked through a little manual styling, of course, but it seems just a little weird, and thought this might help if anyone else is running into issues with Font Awesome icons and inconsistencies between widgets and blocks.  

Hope this is helpful (and makes sense).  Thanks for the plugin!

**Edit**: sorry, spoke too soon.  If there's only a social icons widget on the page, the Font Awesome font doesn't load at all.  If there's also a social icons block, it does.

**Comment by ciorici** [comment]
Hi @tiny-moo 

Thanks for letting us know about this issue.

We've just updated the plugin and now the problem with the Amazon icon should be fixed both in the block and the widget.
