### ISSUE TITLE
Jupiter Theme Control Panel Issue

### ISSUE THREAD

**Issue by jaressloo** [wpzoom/Social-Icons-Widget-by-WPZOOM#4]
Hi,

First off - this plugin is awesome so far! So much flexibility and control! It's exactly what I needed. :)

Quick issue though - 

I'm using the "Jupiter" theme by Art Bees and it looks like after installing this plugin, when I navigate to the theme options page, I'm getting a conflict with vue.js. Can someone take a look? Thank you!

![image](https://user-images.githubusercontent.com/31831277/30253347-f2042640-9650-11e7-97d0-5365db463caf.png)

**Comment by ciorici** [comment]
Hello,

Can you please send us by email a copy of your theme so we can test the plugin?
hello@wpzoom.com

Thanks

**Comment by jaressloo** [comment]
Hello, I provided the copy of the theme to your support people, but it looks like they misunderstood and thought I had one of your themes. I have an ArtBees theme and I was thinking about buying the pro version of the plugin, but...if it doesn't work in the free version, I would have to move away from it. Right now, I have to disable the plugin, make my changes in the management console for the theme, then re-enable the plugin again. Not super ideal. Thank you for your help again!

**Comment by ciorici** [comment]
We've updated the plugin to version 3.0.2 with a fix for this bug:
https://wordpress.org/plugins/social-icons-widget-by-wpzoom/

**Comment by jaressloo** [comment]
AWESOME! Excited to update to this new version. Thank you!!
