### ISSUE TITLE
Academicons

### ISSUE THREAD

**Issue by abers** [wpzoom/Social-Icons-Widget-by-WPZOOM#5]
Would it be possible to add [academicons](https://jpswalsh.github.io/academicons/) to social icons widget?

Edit: Icons for [Lichess](https://lichess.org/) and [Chess.com](https://www.chess.com/) would also be amazing.

**Comment by ciorici** [comment]
@abers Thanks for suggestions.

We'll add some of those icons in the next plugin update.

**Comment by ciorici** [comment]
We've updated the plugin on wp.org to version **3.2.0**, which includes now the Academicons set.

![Pasted_Image_06_04_2019__17_43](https://user-images.githubusercontent.com/1674706/55671798-0a234b00-5894-11e9-94a7-7aa7ada38da9.png)

As for the other 2 icons requested, we couldn't find them in the needed format (svg). I see that there is a Chess icon in the Academicons: Springer. Maybe that would work for you?

![Screen Shot 2019-04-06 at 17 49 08](https://user-images.githubusercontent.com/1674706/55671821-4b1b5f80-5894-11e9-97a4-403ba142bf82.png)

**Comment by abers** [comment]
Thanks for the speed in adding these, much appreciated! The Springer one would do without the text under it. Don't know whether there is a generic Font Awesome chess piece?

**Comment by ciorici** [comment]
@abers You mean the line at the bottom in the Springer icon, as I don't see any text there.

We can try to include a different Chess icon in the next update. Can you help us to find the one that fits best?

https://www.google.com/search?q=chess+icon+svg
https://fontawesome.com/icons?c=chess

Our plugin currently bundles Font Awesome v.4.0, but chess icons are included only in v5.0.

**Comment by abers** [comment]
Ah sorry, I thought the springer icon had text under it based on the picture you posted here. It'll do in the meantime.

In terms of a chess icon the [pawn](https://fontawesome.com/icons/chess-pawn?style=solid) is closest to chess.com and the [knight](https://fontawesome.com/icons/chess-knight?style=solid) closest to lichess. If just wanting a single generic chess icon then king or knight are the pieces most often used.

**Comment by shar0212** [comment]
hello Ciorici,

I have recently tried to use this widget on Ashe-Pro, but the google scholar symbol from Academicons and also the orchid symbol, only shows a square and not the symbol. 

do you have any suggestions?
thnx!
